### PR TITLE
Estca 2022 presentations

### PR DESCRIPTION
**Pull request by ZachAttacksProblems**
Added presentations as own folders.

### CODE REVIEW

**Review by byrcyb — COMMENTED** [review]
For the Ethics in AI presentation it looks good overall with a few minor changes:
- clear cell outputs before committing
- use kebab-case naming convention for ESTCA 2022 ai-for-educators.ipynb file
- .gitignore seems to contain lots of extra items in there that aren't necessary for this presentation notebook

No changes for the Indigenous Culture Through Code presentation.

**Comment by byrcyb** [comment]
Also for the Indigenous Culture presentation, you can probably remove the scripts and resources folders since you don't actually call them in this presentation notebook.

**Comment by ZachAttacksProblems** [comment]
Removed unused images/resources/scripts/etc from both folders.
The presentations should have their cells cleared now.

**Review by byrcyb — APPROVED** [review]
Looks good, thanks for updating.

**Pull request merged**
